swagger: '2.0'
info:
  description: 'Notarization component is system used to notarize text or files in distributed fashion. It exposes RESTful api for which takes multipart/form-data and stores it to IPFS and saves the hash to Ethereum blockchain.'
  version: '1.0.0'
  title: 'Notarization Component'
host: 'localhost:5000'
basePath: '/api/notarization'
tags:
  - name: 'API'
    externalDocs:
      description: 'Find out more'
      url: 'https://github.com/q1kka/notarization-component'
schemes:
  - 'http'
paths:
  /notarize:
    post:
      summary: 'Insert new document'
      description: ''
      tags:
        - API
      operationId: 'insertDoc'
      consumes:
        - 'multipart/form-data'
      produces:
        - 'application/json'
      parameters:
        - in: 'formData'
          name: file
          description: 'Document that needs to be notarized'
          required: true
          type: file
      responses:
        200:
          description: 'OK'
        405:
          description: 'Invalid input'
  /fetch:
    get:
      summary: 'Fetch a file or text'
      description: 'Used to fetch a file or a text'
      tags:
        - API
      operationId: 'fethDoc'
      parameters:
        - in: query
          name: id
          required: true
          type: string
      responses:
        200:
          description: OK
        400:
          description: 'Bad request'
